const { chromium } = require('/home/claude/.npm-global/lib/node_modules/playwright');
const fs = require('fs'), path = require('path');
const file = path.resolve(process.argv[2] || 'b216/testpage/index.html');
let pass = 0, fail = 0;
function ok(c, msg){ if(c){ pass++; console.log('  ✓', msg); } else { fail++; console.log('  ✗', msg); } }
(async () => {
  const src = fs.readFileSync(file, 'utf8').replace('  function _vacUnlimited(id){', '  window.__T=function(c){return eval(c);};\n  function _vacUnlimited(id){');
  const tmp = path.join(path.dirname(file), '_h_r216.html'); fs.writeFileSync(tmp, src);
  const br = await chromium.launch(); const ctx = await br.newContext({ timezoneId:'Asia/Seoul', viewport:{width:1500,height:900} });
  const pg = await ctx.newPage(); const errs=[]; pg.on('pageerror', e => errs.push(String(e)));
  await pg.route('**/*', r => { const u=r.request().url(); if(u.startsWith('file://')) r.continue(); else r.abort(); });
  await pg.goto('file://' + tmp); await pg.waitForTimeout(3500);
  await pg.evaluate(() => { document.getElementById('authGate').style.display='none'; });
  const T = c => pg.evaluate(c2 => window.__T(c2), c);
  const show = () => pg.evaluate(()=>{ document.querySelectorAll('.page-section').forEach(p=>{ if(p.id==='pageEstimate') p.style.display='block'; }); });
  const loadQuote = async () => { await T(`_authUser={id:'kjs',name:'김재성',role:'admin'}; quoteVendors=[{id:'qv1',name:'주식회사 케이에스',count:1}]; _qCurId='qv1'; switchPage('quote');
    _qCart=[{vid:'qv1',vname:'주식회사 케이에스',spec:'LVMK205-5K',name:'VALVE',e:28390,buy:17320,sell:18830,qty:1},{vid:'qv1',vname:'주식회사 케이에스',spec:'KPH04-01',name:'FITTING',e:2800,buy:2100,sell:2420,qty:1}];
    _qLoadedId='q_test'; _qQuoteNo='주식회사 케이에스-20260917-01'; _qCartSave(); renderQCart(); 'ok'`); await pg.waitForTimeout(300); await show(); };
  const lastSpec = () => pg.locator('#qCart tbody input[data-mf="spec"]').last();
  const modal = () => T(`(function(){ var o=document.getElementById('infoOverlay'); return o && o.style.display!=='none' ? o.innerText : ''; })()`);

  console.log('▶ 불러온 견적(psrc 없음) 마지막 줄에서 엔터 두 번 → 새 줄');
  await loadQuote();
  ok(await T(`_qCart[1].psrc==='kph04-01'||_qCart[1].psrc===_qNorm('KPH04-01')`), '그릴 때 가격 출처(psrc) 인정');
  await lastSpec().press('Enter'); await pg.waitForTimeout(200);
  ok(await T(`_qCart[1].sell===2420 && _qCart[1].e===2800`), '첫 엔터: 가격 그대로 (지워지지 않음)');
  ok((await modal())==='', '"규격 변경" 안내창 안 뜸');
  await lastSpec().press('Enter'); await pg.waitForTimeout(300);
  ok(await T(`_qCart.length===3 && _qCart[1].sell===2420`), '두 번째 엔터: 새 줄 추가, 가격 유지');
  console.log('▶ 빈 마지막 줄에서 엔터 → 줄 추가');
  await lastSpec().press('Enter'); await pg.waitForTimeout(300);
  ok(await T(`_qCart.length===4`), '빈 줄에서 엔터 한 번에 새 줄');
  console.log('▶ 행 삽입(아래)');
  await T(`qCartInsertRow(1,true,1); 'ok'`); await pg.waitForTimeout(200);
  ok(await T(`_qCart.length===5 && !_qCart[2].spec && _qCart[1].spec==='KPH04-01'`), 'KPH04-01 아래에 빈 줄 삽입');
  console.log('▶ 규격을 진짜 바꾸면 r200 규칙 유지');
  await loadQuote();
  await pg.evaluate(()=>{ const a=document.querySelectorAll('#qCart tbody input[data-mf="spec"]'); const el=a[a.length-1]; el.value='ZZZ-NOPE-1'; el.dispatchEvent(new Event('input',{bubbles:true})); el.dispatchEvent(new Event('change',{bubbles:true})); });
  await pg.waitForTimeout(250);
  ok(await T(`_qCart[1].spec==='ZZZ-NOPE-1' && _qCart[1].sell==null`), '모르는 규격으로 바꾸면 옛 가격은 지움(r200)');
  ok((await modal()).indexOf('규격이 바뀌어서')>=0, '안내창은 그때만');
  console.log('▶ 같은 값으로 change 가 또 와도 안전');
  await loadQuote();
  await pg.evaluate(()=>{ const a=document.querySelectorAll('#qCart tbody input[data-mf="spec"]'); const el=a[0]; el.dispatchEvent(new Event('change',{bubbles:true})); });
  await pg.waitForTimeout(200);
  ok(await T(`_qCart[0].sell===18830 && _qCart[0].buy===17320`), '값 변화 없는 change → 가격 유지');
  ok(errs.length===0, 'pageerror 0'+(errs.length?(' — '+errs.join(' | ')):''));
  console.log(`\n결과: ${pass}/${pass+fail}`);
  fs.unlinkSync(tmp); await br.close(); process.exit(fail?1:0);
})();
